django_detections/detectitions_webapp/urls.py
from django.urls import path

from . import views


app_name = "polls_app" # app namespace
urlpatterns = [
    path('react/', views.react_app_view, name='react_app_view'),
    path('api/detect/', views.DetectionAPIView.as_view(), name='detection_api'),
    # ex: /polls/ is the URL to use to access the view
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),

]

django_detections/django_detections/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django_detections/detectitions_webapp/models.py
import datetime 

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField("date published")

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		#return self.pub_date >= timezone.now() - datetime.timedelta(days=1) # returns bug for questions in the future
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

django_detections/detectitions_webapp/views.py
import os
import subprocess
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.parsers import MultiPartParser, FormParser
from .serializers import ImageUploadSerializer
from django.conf import settings


from django.shortcuts import render, get_object_or_404

from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from .models import Question, Choice # django database API
from django.template import loader
from django.urls import reverse


# Create your views here.


DARKNET_PATH = os.path.join(settings.BASE_DIR, 'polls_app', 'static', 'darknet')


def index(request):
	latest_question_list = Question.objects.order_by("-pub_date")[:5]
	context = {"latest_question_list": latest_question_list,}  # The context is a dictionary mapping template variable names to Python objects.

	return render(request, "polls/index.html", context) # HttpResponse or use django shotcuts as render with template and context args



def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls_app:results", args=(question.id,))) # url to which user will be redirected, reverse() helps avoid having to hardcode a URL in the view function



def react_app_view(request):
    return render(request, 'index.html')



class DetectionAPIView(APIView):
    parser_classes = (MultiPartParser, FormParser)

    def post(self, request, *args, **kwargs):
        serializer = ImageUploadSerializer(data=request.data)
        if serializer.is_valid():
            image = serializer.validated_data['image']
            image_path = os.path.join(settings.MEDIA_ROOT, image.name)
            
            with open(image_path, 'wb') as destination:
                for chunk in image.chunks():
                    destination.write(chunk)
            
            detections = self.detect_objects(image_path)
            
            os.remove(image_path)
            
            return Response({'detections': detections})
        else:
            return Response(serializer.errors, status=400)

    def detect_objects(self, image_path):
        result = subprocess.check_output([os.path.join(DARKNET_PATH, 'darknet'), 'detector', 'test', '../build/darknet/x64/data/obj.data', '../build/darknet/x64/cfg/yolo-obj.cfg', '../build/darknet/x64/backup/yolo-obj_final.weights', image_path], cwd=DARKNET_PATH, text=True)
        return result

django_detections/detectitions_webapp/templates/polls/detail.html
<!-- <h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul> -->


<form action="{% url 'polls_app:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

django_detections/detectitions_webapp/templates/polls/index.html
{% load static %} 

<link rel="stylesheet" href="{% static 'polls/style.css' %}">


{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls_app:detail' question.id%}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

django_detections/detectitions_webapp/templates/polls/results.html
<!-- <!DOCTYPE html>
<html>
<head>
    <title>Object Detection Results</title>
</head>
<body>
    <h1>Object Detection Results</h1>
    <ul>
        {% for detection in detections %}
            <li>{{ detection }}</li>
        {% endfor %}
    </ul>
</body>
</html>
 -->


<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls_app:detail' question.id %}">Vote again?</a>

django_detections/detectitions_webapp/templates/polls/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Image</title>
</head>
<body>
    <h1>Upload an Image</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload and Detect</button>
    </form>
</body>
</html>